#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE n8n;
    CREATE DATABASE flowise;
    CREATE DATABASE zep;
    CREATE DATABASE openwebui;
    CREATE DATABASE langflow;
    GRANT ALL PRIVILEGES ON DATABASE n8n TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE flowise TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE zep TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE openwebui TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE langflow TO "$POSTGRES_USER";
EOSQL
